name: Release & Upload artifacts

# on:
#   push:
#     tags:
#       - "v*.*.*"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package Application (Linux)
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: src
      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: GPX_elevation
          path: src/dist/linux
      - name: Package Application (Windows)
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: GPX_elevation.exe
          path: src/dist/windows
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
            src/dist/windows/GPX_elevation.exe
            src/dist/linux/GPX_elevation